use std::path::{Path, PathBuf};
use std::process::Command as SyncCommand;

use futou_core::ports::process_manager::{ProcessError, ProcessManager};
use tracing::{info, warn};

pub struct WindowsProcessManager;

fn find_exe(bin_dir: &Path, names: &[&str]) -> Option<PathBuf> {
    for name in names {
        let p = bin_dir.join(name);
        if p.exists() {
            return Some(p);
        }
    }
    None
}

fn data_initialized(data_dir: &Path) -> bool {
    data_dir.exists() && data_dir.join("mysql").exists()
        || data_dir.join("ibdata1").exists()
        || data_dir.join("PG_VERSION").exists()
}

fn write_config(dir: &Path, name: &str, content: &str) -> Result<(), ProcessError> {
    let _ = std::fs::create_dir_all(dir);
    std::fs::write(dir.join(name), content)
        .map_err(|e| ProcessError::Io(format!("write {}: {}", name, e)))
}
impl WindowsProcessManager {
    fn default_port(runtime: &str) -> Option<u16> {
        match runtime {
            "mariadb" | "mysql" => Some(3306),
            "postgresql" => Some(5432),
            "apache" | "nginx" => Some(80),
            _ => None,
        }
    }
}

fn generate_apache_config(
    server_root: &Path,
    conf_dir: &Path,
    document_root: &Path,
) -> Result<(), ProcessError> {
    let php_installed = false;
    let mut conf = format!(
        r#"# Generated by futou
ServerRoot "{}"
Listen 80
ServerName localhost

LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule dir_module modules/mod_dir.so
LoadModule mime_module modules/mod_mime.so

DocumentRoot "{}"
<Directory "{}">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<IfModule dir_module>
    DirectoryIndex index.html index.php
</IfModule>

"#,
        server_root.display(),
        document_root.display(),
        document_root.display(),
    );

    if php_installed {
        conf.push_str(
            r#"
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
<FilesMatch \.php$>
    SetHandler proxy:fcgi://127.0.0.1:9000
</FilesMatch>
"#,
        );
    }

    write_config(conf_dir, "httpd.conf", &conf)
}

fn generate_nginx_config(conf_dir: &Path, document_root: &Path) -> Result<(), ProcessError> {
    let escaped = document_root.display().to_string().replace('\\', "/");
    let conf = format!(
        r#"# Generated by futou
worker_processes 1;
error_log logs/error.log;
pid logs/nginx.pid;

events {{
    worker_connections 1024;
}}

http {{
    include mime.types;
    default_type application/octet-stream;
    access_log logs/access.log;

    server {{
        listen 80;
        server_name localhost;
        root {root};
        index index.html index.php;

        location / {{
            try_files $uri $uri/ =404;
        }}
    }}
}}
"#,
        root = escaped,
    );
    write_config(conf_dir, "nginx.conf", &conf)
}

#[async_trait::async_trait]
impl ProcessManager for WindowsProcessManager {
    async fn start_server(
        &self,
        runtime: &str,
        bin_dir: &Path,
        data_dir: &Path,
        document_root: Option<&Path>,
    ) -> Result<u32, ProcessError> {
        match runtime {
            "mariadb" | "mysql" => {
                let port = Self::default_port(runtime).unwrap_or(3306);
                let exe = find_exe(bin_dir, &["mariadbd.exe", "mysqld.exe"]).ok_or_else(|| {
                    ProcessError::Io(format!("mariadbd not found in {:?}", bin_dir))
                })?;

                info!(
                    "Starting MariaDB: {:?} --datadir={:?} --port={}",
                    exe, data_dir, port
                );
                let child = tokio::process::Command::new(&exe)
                    .arg(format!("--datadir={}", data_dir.display()))
                    .arg(format!("--port={}", port))
                    .stdout(std::process::Stdio::null())
                    .stderr(std::process::Stdio::null())
                    .spawn()
                    .map_err(|e| ProcessError::Io(format!("spawn mariadbd: {}", e)))?;

                Ok(child.id().unwrap_or(0))
            }
            "postgresql" => {
                let port = Self::default_port(runtime).unwrap_or(5432);
                let pg_ctl = bin_dir.join("pg_ctl.exe");
                if !pg_ctl.exists() {
                    return Err(ProcessError::Io(format!(
                        "pg_ctl not found in {:?}",
                        bin_dir
                    )));
                }

                info!(
                    "Starting PostgreSQL: {:?} -D {:?} -p {}",
                    pg_ctl, data_dir, port
                );
                let child = tokio::process::Command::new(&pg_ctl)
                    .arg("start")
                    .arg("-D")
                    .arg(data_dir)
                    .arg("-l")
                    .arg(data_dir.join("pg.log"))
                    .arg("-o")
                    .arg(format!("-p {}", port))
                    .stdout(std::process::Stdio::null())
                    .stderr(std::process::Stdio::null())
                    .spawn()
                    .map_err(|e| ProcessError::Io(format!("spawn pg_ctl: {}", e)))?;

                Ok(child.id().unwrap_or(0))
            }
            "apache" => {
                let doc_root = document_root.ok_or_else(|| {
                    ProcessError::Io("document_root is required for Apache".into())
                })?;
                let conf_dir = data_dir.join("conf");
                generate_apache_config(bin_dir, &conf_dir, doc_root)?;

                let exe = bin_dir.join("bin").join("httpd.exe");
                if !exe.exists() {
                    return Err(ProcessError::Io(format!(
                        "httpd.exe not found in {:?}",
                        bin_dir.join("bin")
                    )));
                }
                info!(
                    "Starting Apache: {:?} -f {:?} -d {:?}",
                    exe,
                    conf_dir.join("httpd.conf"),
                    bin_dir
                );
                let child = tokio::process::Command::new(&exe)
                    .arg("-f")
                    .arg(conf_dir.join("httpd.conf"))
                    .arg("-d")
                    .arg(bin_dir)
                    .stdout(std::process::Stdio::null())
                    .stderr(std::process::Stdio::null())
                    .spawn()
                    .map_err(|e| ProcessError::Io(format!("spawn httpd: {}", e)))?;

                Ok(child.id().unwrap_or(0))
            }
            "nginx" => {
                let doc_root = document_root.ok_or_else(|| {
                    ProcessError::Io("document_root is required for Nginx".into())
                })?;
                let conf_dir = data_dir.join("conf");
                let _ = std::fs::create_dir_all(data_dir.join("logs"));
                generate_nginx_config(&conf_dir, doc_root)?;

                let exe = bin_dir.join("nginx.exe");
                if !exe.exists() {
                    return Err(ProcessError::Io(format!(
                        "nginx.exe not found in {:?}",
                        bin_dir
                    )));
                }
                info!(
                    "Starting Nginx: {:?} -p {:?} -c {:?}",
                    exe,
                    data_dir,
                    conf_dir.join("nginx.conf")
                );
                let child = tokio::process::Command::new(&exe)
                    .arg("-p")
                    .arg(data_dir)
                    .arg("-c")
                    .arg(conf_dir.join("nginx.conf"))
                    .stdout(std::process::Stdio::null())
                    .stderr(std::process::Stdio::null())
                    .spawn()
                    .map_err(|e| ProcessError::Io(format!("spawn nginx: {}", e)))?;

                Ok(child.id().unwrap_or(0))
            }
            _ => Err(ProcessError::NotServer(runtime.to_string())),
        }
    }

    async fn stop_server(&self, pid: u32) -> Result<(), ProcessError> {
        if pid == 0 {
            return Ok(());
        }
        info!("Stopping process PID {}", pid);
        let output = SyncCommand::new("taskkill")
            .args(["/PID", &pid.to_string()])
            .output()
            .map_err(|e| ProcessError::Io(format!("taskkill: {}", e)))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            warn!("taskkill PID {} returned non-zero: {}", pid, stderr.trim());
        }
        Ok(())
    }

    async fn init_data_dir(
        &self,
        runtime: &str,
        bin_dir: &Path,
        data_dir: &Path,
    ) -> Result<(), ProcessError> {
        if data_initialized(data_dir) {
            info!("Data dir {:?} already initialized, skipping", data_dir);
            return Ok(());
        }

        let _ = std::fs::create_dir_all(data_dir);

        match runtime {
            "mariadb" | "mysql" => {
                let init_exe =
                    find_exe(bin_dir, &["mariadb-install-db.exe", "mysql_install_db.exe"])
                        .ok_or_else(|| {
                            ProcessError::Io(format!("mysql_install_db not found in {:?}", bin_dir))
                        })?;

                info!(
                    "Initializing MariaDB data dir: {:?} --datadir={:?}",
                    init_exe, data_dir
                );
                let output = tokio::process::Command::new(&init_exe)
                    .arg(format!("--datadir={}", data_dir.display()))
                    .stdout(std::process::Stdio::null())
                    .stderr(std::process::Stdio::piped())
                    .output()
                    .await
                    .map_err(|e| ProcessError::Io(format!("init: {}", e)))?;

                if !output.status.success() {
                    let stderr = String::from_utf8_lossy(&output.stderr);
                    return Err(ProcessError::ExitError(format!(
                        "mysql_install_db: {}",
                        stderr
                    )));
                }
            }
            "postgresql" => {
                let initdb = bin_dir.join("initdb.exe");
                if !initdb.exists() {
                    return Err(ProcessError::Io(format!(
                        "initdb not found in {:?}",
                        bin_dir
                    )));
                }

                info!(
                    "Initializing PostgreSQL data dir: {:?} -D {:?}",
                    initdb, data_dir
                );
                let output = tokio::process::Command::new(&initdb)
                    .arg("-D")
                    .arg(data_dir)
                    .arg("--no-locale")
                    .arg("-E")
                    .arg("UTF8")
                    .stdout(std::process::Stdio::null())
                    .stderr(std::process::Stdio::piped())
                    .output()
                    .await
                    .map_err(|e| ProcessError::Io(format!("initdb: {}", e)))?;

                if !output.status.success() {
                    let stderr = String::from_utf8_lossy(&output.stderr);
                    return Err(ProcessError::ExitError(format!("initdb: {}", stderr)));
                }
            }
            _ => return Err(ProcessError::NotServer(runtime.to_string())),
        }

        info!("Data dir initialized: {:?}", data_dir);
        Ok(())
    }
}
